volumes:
  mongocfg: {}
  mongodb: {}

services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - "mongocfg:/data/configdb"
      - "mongodb:/data/db"
